name = "worker-aged-bush-cc6a"
type = "webpack"
account_id = "e98a1f01bbc53d0d784c99f0c4691fef"
workers_dev = true
webpack_config = "webpack.config.js"

# Define the route to match /flutterapp and proxy it to the desired destination
[[routes]]
pattern = "www.pitmtech.com/flutterapp/*"
script = "workers-site"
