// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFNfJqUV58FOgs6_9Uzpld6hsKBZZaYYI',
    appId: '1:298714277530:web:eb62931357c3ab4423e123',
    messagingSenderId: '298714277530',
    projectId: 'lntchatapp',
    authDomain: 'lntchatapp.firebaseapp.com',
    storageBucket: 'lntchatapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDy6tuErhg78zILEEG4m1MRqHLcoo0hYI',
    appId: '1:298714277530:android:9ee095200d01be2923e123',
    messagingSenderId: '298714277530',
    projectId: 'lntchatapp',
    storageBucket: 'lntchatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcrQ930RoD9SE_-LH-Fwex6ViW0aviSIc',
    appId: '1:298714277530:ios:c3a3ca2d23d782d323e123',
    messagingSenderId: '298714277530',
    projectId: 'lntchatapp',
    storageBucket: 'lntchatapp.appspot.com',
    iosBundleId: 'com.example.messaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcrQ930RoD9SE_-LH-Fwex6ViW0aviSIc',
    appId: '1:298714277530:ios:28ca812f870e8a8d23e123',
    messagingSenderId: '298714277530',
    projectId: 'lntchatapp',
    storageBucket: 'lntchatapp.appspot.com',
    iosBundleId: 'com.example.messaging.RunnerTests',
  );
}
